### ISSUE TITLE
Public view of screenshots front end

### ISSUE THREAD

**Issue by Lukewh** [canonical-websites/snapcraft.io#388] opened 2018-03-14 14:35 UTC

**Comment by matthewpaulthomas** [comment] 2018-03-14 15:07
Duplicate of [snapcraft.io#344](https://github.com/canonical-websites/snapcraft.io/issues/344).

**Closed by matthewpaulthomas** 2018-03-14 15:07 UTC

**Comment by Lukewh** [comment] 2018-03-14 15:09
Thanks @matthewpaulthomas
