### ISSUE TITLE
"Registering snap" button not present on "new pages"

### ISSUE THREAD

**Issue by OleMussmann** [canonical-websites/snapcraft.io#1333] opened 2018-11-18 14:15 UTC
### Expected behaviour
Helpdocs say: To register a name, log into your [developer account](https://snapcraft.io/account
) and click “Register snap.” Expected behaviour is to find a button "Register snap" there.

### Steps to reproduce the problem
Go to [developer account](https://snapcraft.io/account) and be forwarded to [https://snapcraft.io/snaps](https://snapcraft.io/snaps). See no "Register snap" button. Scratch head. Find missing function under [https://dashboard.snapcraft.io/register-snap/](https://dashboard.snapcraft.io/register-snap/).

### Specs
URL retrieved 2018-11-18.

- _URL:_ https://snapcraft.io/account
- _Operating system:_ Linux
- _Browser:_ Firefox

**Comment by matthewpaulthomas** [comment] 2018-11-18 16:07
@OleMussmann Thanks for the report. Could you attach a screenshot of what you do see on that page? The “Register snap” button shows up for me:

![1333-register-snap](https://user-images.githubusercontent.com/19801137/48675066-ea40f400-eb4b-11e8-87ad-87758f06683b.png)

**Comment by OleMussmann** [comment] 2018-11-19 02:30
@matthewpaulthomas Thanks for your reply. Apparently this only happens when you have no snaps yet. I can reproduce your screenshot with my normal account. However, I made an empty test-account and there I find the screenshot below without "Register snap" button:

![snaps](https://user-images.githubusercontent.com/14004859/48682857-b1595b80-ebed-11e8-9205-cd48f2756df3.png)

**Comment by matthewpaulthomas** [comment] 2018-11-19 13:49
Thanks for clarifying. This is a duplicate of #1276.

**Closed by matthewpaulthomas** 2018-11-19 13:49 UTC
