### ISSUE TITLE
Filing a name dispute is cumbersome

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/snapcraft.io#1008] opened 2018-08-10 09:00 UTC
Filing a dispute should be straightforward. Attempt to register a name, click on the "file a dispute" link when it's taken, and fill out the dispute form.

However, the process currently is:
1. Attempt to register a name
1. Click on the "file a dispute link". The name registration page from the old dashboard site appears.
1. Fill in this additional name registration and click submit
1. Read that the name is taken and hit submit again to file the dispute

## To reproduce

Attempt to register "core" as a snap name.

**Comment by Greggless** [comment] 2018-08-16 16:16
Could we send users to the forum to make a (private) request there?

**Comment by matthewpaulthomas** [comment] 2018-08-19 10:12
@Greggless I think sending people to the forum would make things worse rather than better. You’d need to create a forum account, because forum.snapcraft.io (unlike dashboard.snapcraft.io) doesn’t yet use SSO. And you’d be more likely to fail the task in other ways, too — for example, by mistyping the name (unlike the dashboard.snapcraft.io form where it’s pre-filled), or by forgetting to provide evidence that you own the name (unlike the dashboard.snapcraft.io form where there’s a specific field for it, though it could be labelled better).

The long-term solution is to provide a complete name-dispute UI inside snapcraft.io (#852). But there might be a short-term solution: replacing the “file a dispute” link with a button that re-submits the registration to dashboard.snapcraft.io, even though it will fail, just so that dashboard.snapcraft.io will show you the dispute form. That would be less cumbersome because it would skip @evandandrea’s step 3.

Maybe that’s not practical, if SSO either doesn’t receive or doesn’t resend a POST form submission when dashboard.snapcraft.io sends you there to sign in. If there’s no short-term solution, then this is a duplicate of #852.

**Comment by matthewpaulthomas** [comment] 2018-08-20 12:41
Ah, ok. I interpreted #852’s “No way to file dispute here’ as “No way to file dispute on the same site”.

I’ve reported [LP#1787947](https://launchpad.net/bugs/1787947) for implementing the missing API.

**Comment by therealjuan** [comment] 2018-12-10 17:38
[Link to specifications for current proposal solution](https://docs.google.com/document/d/1_YSBu1D1wHZQgWksi1_ronMkvTawCH6mnU-PprwHuP0/edit#heading=h.4nc7zj32ypw9)

**Comment by matthewpaulthomas** [comment] 2018-12-11 17:17
[Register a snap name](https://docs.google.com/document/d/1_YSBu1D1wHZQgWksi1_ronMkvTawCH6mnU-PprwHuP0/edit#heading=h.omtxwnjiunb):
- The focus here is on one case where name registration fails. But most of the time, registration succeeds, right? If so, I think it would be clearer to name the initial button “Register” rather than “Continue”. (There are dozens of ways in which printing can fail, but the main button in a print dialog is still “Print”, not “Continue”.)

[Prompt to file a dispute or register a new name](https://docs.google.com/document/d/1_YSBu1D1wHZQgWksi1_ronMkvTawCH6mnU-PprwHuP0/edit#heading=h.fyeb46q29pjv):
- Did you consider showing the error as a validation error on the name field instead? That’s the usual behavior for this kind of error, and it has several advantages: less UI overall, more visible context, easier corrections, no need to remember the suggested alternative name, and (eventually) the possibility of showing the error even before submitting the form. “File a dispute” could be a link within the inline error message.
- It’s not clear what the X button will do: return you to the form, to try a different name, or cancel the registration altogether (which is a reasonable possibility, if you realise that one of your colleagues registered the name before you did). This is an example of why we generally avoid close buttons in dialogs.
- If the existing snap is public, has releases, and has developer contact info, perhaps there should be an option to contact the publisher?

[File a dispute form](https://docs.google.com/document/d/1_YSBu1D1wHZQgWksi1_ronMkvTawCH6mnU-PprwHuP0/edit#heading=h.93dgu8fj98mq):
- “Dispute the name” would be a bit less abstract (and shorter) than “File a name dispute for”. (Or if less confrontational would be better, “Claim the name”.)
- Someone could quite reasonably parse “You can request the existing snap name to be revoked from its current owner” as “You can request {the existing snap name to be revoked} from its current owner” — that is, that your comments will be sent merely to the current owner, nobody else. And there’s nothing here to say that anything different will happen.
- As above, it’s a bit odd that we refer twice to “the current owner” without mentioning who they are. If you’re in a large enough company, you might not be aware that the registrant is someone in the same building, and the problem would be much more easily resolved by walking over to their office and getting them to add you as a collaborator. If the snap is private or unreleased, maybe we can’t reveal the owner to avoid spoiling surprises. But in that case we shouldn’t mention “the current owner” at all; just focus on “Why you have rights to this name”.

[Name dispute confirmation](https://docs.google.com/document/d/1_YSBu1D1wHZQgWksi1_ronMkvTawCH6mnU-PprwHuP0/edit#heading=h.repzpeslx2z3):
- Is it really likely that “Register a new name” is what someone will want to do at this point? Maybe if they’re registering several names in a row, but not otherwise. Maybe just “Return to my snaps” is enough.

**Comment by therealjuan** [comment] 2018-12-11 17:52
[Specs updated](https://docs.google.com/document/d/1_YSBu1D1wHZQgWksi1_ronMkvTawCH6mnU-PprwHuP0/edit#)

## Register a snap name:
> 
> The focus here is on one case where name registration fails. But most of the time, registration succeeds, right? If so, I think it would be clearer to name the initial button “Register” rather than “Continue”. (There are dozens of ways in which printing can fail, but the main button in a print dialog is still “Print”, not “Continue”.)

👍 

![02a register a new snap](https://user-images.githubusercontent.com/8167677/49818674-3f4ae100-fd6b-11e8-887e-cf538b65cf87.png)

## Prompt to file a dispute or register a new name:
> 
> Did you consider showing the error as a validation error on the name field instead? That’s the usual behavior for this kind of error, and it has several advantages: less UI overall, more visible context, easier corrections, no need to remember the suggested alternative name, and (eventually) the possibility of showing the error even before submitting the form. “File a dispute” could be a link within the inline error message.
> It’s not clear what the X button will do: return you to the form, to try a different name, or cancel the registration altogether (which is a reasonable possibility, if you realise that one of your colleagues registered the name before you did). This is an example of why we generally avoid close buttons in dialogs.
> If the existing snap is public, has releases, and has developer contact info, perhaps there should be an option to contact the publisher?

I actually considered so revamping the alternative design here :)

![02a register a new snap copy](https://user-images.githubusercontent.com/8167677/49819169-9d2bf880-fd6c-11e8-950d-1cf7f0aaa69d.png)


## File a dispute form:
> 
> “Dispute the name” would be a bit less abstract (and shorter) than “File a name dispute for”. (Or if less confrontational would be better, “Claim the name”.)
> Someone could quite reasonably parse “You can request the existing snap name to be revoked from its current owner” as “You can request {the existing snap name to be revoked} from its current owner” — that is, that your comments will be sent merely to the current owner, nobody else. And there’s nothing here to say that anything different will happen.
> As above, it’s a bit odd that we refer twice to “the current owner” without mentioning who they are. If you’re in a large enough company, you might not be aware that the registrant is someone in the same building, and the problem would be much more easily resolved by walking over to their office and getting them to add you as a collaborator. If the snap is private or unreleased, maybe we can’t reveal the owner to avoid spoiling surprises. But in that case we shouldn’t mention “the current owner” at all; just focus on “Why you have rights to this name”.

👍 

![03 file a dispute](https://user-images.githubusercontent.com/8167677/49818780-83d67c80-fd6b-11e8-9eb1-80d93a3a4268.png)

## Name dispute confirmation:
> 
> Is it really likely that “Register a new name” is what someone will want to do at this point? Maybe if they’re registering several names in a row, but not otherwise. Maybe just “Return to my snaps” is enough.

👍 

![04 confirmation](https://user-images.githubusercontent.com/8167677/49818790-8a64f400-fd6b-11e8-9e82-21b784d8450a.png)

**Comment by matthewpaulthomas** [comment] 2018-12-16 14:10
Good work. Now that I read the text with most mentions of “the current owner” removed, I’m more confident in suggesting that we use “claim” rather than “dispute” throughout. It’s less antagonistic, better conveys what someone’s trying to achieve (receiving ownership of the name), and it would allow using the same text for the case where they’re trying to register a reserved name that doesn’t actually have a current owner.

I won’t nitpick the rest of the text, except for one potentially misleading detail: “i.e.” should be “e.g.” (or even better, “for example” — otherwise people might think our suggestion is the only possible choice.

**Comment by therealjuan** [comment] 2018-12-16 19:03
So updating the latest feedback, here are the latest mockups:

![02a register a new snap](https://user-images.githubusercontent.com/8167677/50057644-2a07f500-0165-11e9-8292-3f243fff50a6.png)
![02a register a new snap copy](https://user-images.githubusercontent.com/8167677/50057645-2aa08b80-0165-11e9-8cf9-488bf59b09f7.png)
![03 file a dispute](https://user-images.githubusercontent.com/8167677/50057647-2aa08b80-0165-11e9-9f09-cad2624c25e2.png)
![04 confirmation](https://user-images.githubusercontent.com/8167677/50057646-2aa08b80-0165-11e9-9e7b-ece12246bfb9.png)

**Closed by therealjuan** 2018-12-16 19:03 UTC
Labels: Priority: Medium, Review: UX +1

**Comment by nessita** [comment] 2019-02-04 20:11
Hello all, specially @therealjuan.

The dashboard API for filing name disputes is ready in production and documented at: https://dashboard.snapcraft.io/docs/api/snap.html#register-a-snap-name-dispute

Please read the docs and let me know if you have any questions.

Cheers, Natalia.
