### ISSUE TITLE
Snap channels inaccurate on snapcraft.io

### ISSUE THREAD

**Issue by nottrobin** [canonical-websites/snapcraft.io#938] opened 2018-07-26 10:07 UTC
For my documentation-builder snap, I recently promoted 1.6.0 to stable and candidate. Then I realised that actually there's no point having candidate point to the same release as stable, so I closed the candidate channel.

Now, `snap info documentation-builder` shows the "candidate" channel as closed, but the website (at `https://snapcraft.io/account/snaps/documentation-builder/release`) still shows the "candidate" channel pointing to `1.6.0`:

![documentation-builder-revisions](https://user-images.githubusercontent.com/519935/43256262-1e153e04-90c4-11e8-8d0f-88e904124d86.png)

**Comment by bartaz** [comment] 2018-07-26 10:09
This seems to be caused by the fact that the only data we have currently on revisions page is revisions history.

Snapcraft.io backend for this view should also have channel map data, so we have more accurate information about released revisions and state of the channels.

**Comment by Lukewh** [comment] 2018-07-30 15:35
The new v2 endpoint is now on staging - once that lands on prod we should switch over and see if it solves this issue @bartaz.

**Comment by Lukewh** [comment] 2018-09-14 13:33
This should have been fixed by https://github.com/canonical-websites/snapcraft.io/pull/1053. Closing this issue, please reopen it with a comment if you still get the issue @nottrobin

**Closed by Lukewh** 2018-09-14 13:33 UTC
