### ISSUE TITLE
“Sign in / register” isn’t clearly developer only

### ISSUE THREAD

**Issue by evandandrea** [canonical-websites/snapcraft.io#877] opened 2018-07-09 11:41 UTC
The “Sign in / register” link on every snapcraft.io page isn’t clear on being just for developer accounts. If you land on snapcraft.io/store you might reasonably think you need to create an account to install apps, which you do not.
![12621c95-fffb-4410-8d70-59e7c3100a42](https://user-images.githubusercontent.com/1523179/42448561-72106bd4-8375-11e8-81fd-11031d3700da.jpeg)

**Comment by therealjuan** [comment] 2018-07-09 13:22
duplicate of [#859](https://github.com/canonical-websites/snapcraft.io/issues/859)

**Closed by therealjuan** 2018-07-09 13:22 UTC
