### ISSUE TITLE
Developer unable to make snap private

### ISSUE THREAD

**Issue by popey** [canonical-websites/snapcraft.io#1360] opened 2018-11-26 18:35 UTC
The developer of the snapraid package wanted to make it private. It's not been touched for a long time, and they don't have time to maintain it.

When they try to switch the privacy field at https://snapcraft.io/snapraid/settings it does this error "`The 'description' field cannot contain control or private unicode characters.`". 

![image](https://user-images.githubusercontent.com/1841272/49034455-ee9f8980-f1a9-11e8-8e5b-a2648f9f1608.png)

The description is however:-

```
SnapRAID stores parity information of your data and it recovers from up to six disk failures.
It is mainly targeted for a home media center, with a lot of big files that rarely change.
```

**Comment by tbille** [comment] 2018-11-28 10:49
@popey I can't reproduce this bug and it seems that you managed to make the snap private. Can you ping me in this issue if you see this bug again.

**Comment by popey** [comment] 2018-11-28 12:51
I didn't make it private, roadmr did. Dunno if he used special powers, but the user was _not_ able to do this.

**Comment by tbille** [comment] 2018-12-19 15:12
@popey I am closing this issue since no one complained about it and couldn't reproduce it. 

If you come across this issue again reopen it and ping me so that I can test it before you ask the snapstore team to fix :smile:

**Closed by tbille** 2018-12-19 15:12 UTC
