### ISSUE TITLE
Publisher snap name doesn't match on storefront and details page

### ISSUE THREAD

**Issue by kwm14** [canonical-websites/snapcraft.io#1773] opened 2019-04-03 13:16 UTC
### Expected behavior
Publisher name matches on the storefront and associated details page.

**Storefront** 
![Screenshot 2019-04-03 at 14 02 38](https://user-images.githubusercontent.com/17748020/55481483-68dd9000-561a-11e9-964e-830de2046deb.png)

### Steps to reproduce the problem
- Check https://snapcraft.io/search?category=featured
- View the **clementine** snap
- Notice snap publisher name is **kz6fittycent**

**Storefront** 
![Screenshot 2019-04-03 at 14 02 52](https://user-images.githubusercontent.com/17748020/55481525-7dba2380-561a-11e9-851f-25d7cc129b3e.png)

- Click snap to view the details page
- Notice snap publisher name displays **James Tigert (kz6fittycent)**

**Snap details** 
![Screenshot 2019-04-03 at 14 01 45](https://user-images.githubusercontent.com/17748020/55481508-772bac00-561a-11e9-8b5a-70863fc57183.png)

**Comment by matthewpaulthomas** [comment] 2019-04-05 10:53
Duplicate of #1656.

**Closed by matthewpaulthomas** 2019-04-05 10:53 UTC
